language: python
python:
  - "3.7"

branches:
  only:
    - staging

env : DJANGO_SETTINGS_MODULE= « purbeurre.settings.travis »

before_script:
  - pip install -r requirements.txt
  - psql -c 'create database travis_ci_test;' -U postgres

services:
  - postgresql

script:
  - python manage.py migrate
  - python -m unittest
